FROM golang:1.18-alpine AS build

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN mkdir data
RUN mkdir grpc
RUN mkdir grpc/client
RUN mkdir grpc/message
RUN mkdir grpc/server

COPY data/*.go data
COPY grpc/client/*.go grpc/client
COPY grpc/message/*.go grpc/message
COPY grpc/server/*.go grpc/server

RUN go build -o grpc-client grpc/client/main.go
RUN go build -o grpc-server grpc/server/main.go

FROM alpine:3.16

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/grpc-client grpc-client
COPY --from=build /usr/src/app/grpc-server grpc-server

CMD [ "./grpc-server" ]
