FROM golang:1.18-alpine

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN mkdir data
RUN mkdir rest
RUN mkdir rest/client
RUN mkdir rest/server

COPY data/*.go data
COPY rest/client/*.go rest/client
COPY rest/server/*.go rest/server

RUN go build -o rest-client rest/client/main.go
RUN go build -o rest-server rest/server/main.go

EXPOSE 8080

CMD [ "./rest-server" ]
