FROM golang:1.18-alpine AS build

WORKDIR /usr/src/app

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN mkdir data
RUN mkdir rest
RUN mkdir rest/client
RUN mkdir rest/server

COPY data/*.go data
COPY rest/client/*.go rest/client
COPY rest/server/*.go rest/server

RUN go build -o rest-client rest/client/main.go
RUN go build -o rest-server rest/server/main.go

FROM alpine:3.16

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/rest-client rest-client
COPY --from=build /usr/src/app/rest-server rest-server

CMD [ "./rest-server" ]
